### ISSUE TITLE
MEL expression were not getting properly migrated. Eg XMLModule, Xpath

### ISSUE THREAD

**Issue by github-amitpandey** [mulesoft/mule-migration-assistant#449]

**Comment by pentreathm** [comment]
@github-amitpandey the Mule Migration Assistant is a best effort tool and currently only translate a list of expressions that are considered the most used based on data. 
If you have cases where the expression is not fully migrated or even not migrated and you use that expression a lot in your apps, you could contribute to the project adding an expression migrator, please check the following guide: 
 
https://github.com/mulesoft/mule-migration-assistant/blob/master/CONTRIBUTING.md#contribute-a-new-expression-migration-to-mma

In any other case, if you see a bug, please try to isolate the expression in a simple Mule 3 app and add the source code so that the issue can be reproduced.
