### ISSUE TITLE
Exclusions .gitignore should not be excluded

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#460]
The class CopyFileVisitor uses the Exclusions Enumeration. 

There is a exclusion for 

` GIT(File.separator + ".gitignore"),`

this should be removed

And add catalog exlusion

**Comment by mlischetti** [comment]
We've added .gitignore file into exclusions because even copying this file from mule 3 project some changes has to be done to add needed exclusions by Studio 7

**Comment by holiday-sunrise** [comment]
which changes ? if you migrate the api inside a devops there have to be a .gitignore file !!!

**Comment by holiday-sunrise** [comment]
maybe we can create a post migraten step "CreateIrnoreFile" a new .gitignore file will be created "Studio 7" dependend

**Comment by afelisatti** [comment]
Yes, thanks, @holiday-sunrise. We are evaluating options here. Ideally, we believe the tool should merge the new Studio 7 requirements with any existing data in the file. Since this could take some time to implement, we think an option to preserve the file could help in the meantime. What do you think?
