### ISSUE TITLE
Parent in PomModel is missing

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#466]
add Parent to PomModel that migration inside the pom.xml is possible

**Comment by mlischetti** [comment]
Hi @holiday-sunrise
Can you please try to explain more deeply the issue that your are facing? 
An example, mule 3 app or expected behaviour would be useful to understand current issue

**Comment by holiday-sunrise** [comment]
all our mule api´s are using an parent with our company settings. the parent have to be changed during the migration. with the option das the parent ist available in the pommodel we are able to write our own migration step

**Comment by afelisatti** [comment]
Hi, @holiday-sunrise! If I understand correctly, you want to add the parent entity to MMA's pom model, then use it in your own internal step? 
We are confused because we noticed in the PR that there are no uses for the parent entity. Your feedback will help us understand the use case and evaluate improving the tool, so parents are accounted for without the need to code a custom step.

**Comment by holiday-sunrise** [comment]
See my comments in th PR
