### ISSUE TITLE
Cleanup code: organise imports according to contribution guidelines

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#486]
Fix: remove the imports.

**Comment by holiday-sunrise** [comment]
any questions ?

**Comment by afelisatti** [comment]
Hi again, @holiday-sunrise. Thanks for reporting this and all your recent contributions! @mlischetti and I reviewed this yesterday. Since the change involves so many files and the import configuration can be specific to each user, we will tackle this ourselves once all your pending contributions are merged and close your matching PR in the meantime. 
This way, we can avoid any disruptions to the PRs in progress and make sure all imports are organized with the contribution guidelines order. We apologize in advance for not noticing the imports did not match the proposed guideline. 
Cheers!

**Comment by holiday-sunrise** [comment]
they do it :-)
