### ISSUE TITLE
Simple expression featuring dw() function fails to be migrated

### ISSUE THREAD

**Issue by holiday-sunrise** [mulesoft/mule-migration-assistant#490]
exp.:

dw("flowVars.applicationProperties.'cloudapp.application.md5' == flowVars.platformApplicationMd5")

should be

dw("vars.applicationProperties.'cloudapp.application.md5' == vars.platformApplicationMd5")

**Comment by afelisatti** [comment]
Hi, @holiday-sunrise! Thanks for reporting this. The problem here seems to be the `dw()` function which is not available in Mule 4: changing `flowVars` to `vars` is not enough to make this work. Unfortunately, we will have to close the PR since the expression migrator should be changed instead. 
We will analyze if simple usages of `dw()` could be migrated and advanced uses that make migration impossible reported. In this case, for example, it looks like the function can be omitted and the internal expression used with `vars`: `vars.applicationProperties.'cloudapp.application.md5' == vars.platformApplicationMd5`.  Does that migration make sense for the app you had?

**Comment by holiday-sunrise** [comment]
We as C4E add some documentation that the BG did not run in this behavior. 

Docu: add a precondition  while using the "mma" and not the the "obi mma"
